//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangTiecCuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatSanh
    {
        public int MaDatSanh { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<decimal> SDTKhach { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> MaSanh { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<int> MaTD { get; set; }
        public Nullable<int> MaDV { get; set; }
        public string Ca { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual Sanh Sanh { get; set; }
        public virtual Thuc_Don Thuc_Don { get; set; }
    }
}
