//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangTiecCuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongThucDon
    {
        public int MaMA { get; set; }
        public int MaTD { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual Thuc_Don Thuc_Don { get; set; }
    }
}
