//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangTiecCuoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanh()
        {
            this.DatSanhs = new HashSet<DatSanh>();
        }
    
        public int MaSanh { get; set; }
        public string TenSanh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatSanh> DatSanhs { get; set; }
    }
}
